---
- name: Install linux-modules-extra-raspi
  ansible.builtin.apt:
    name: linux-modules-extra-raspi
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_architecture == 'aarch64'
    - ansible_kernel is match(".*raspi$")
  register: result
- name: Install snapd
  become: true
  become_user: root
  ansible.builtin.apt:
    name: snapd
    state: present
  register: result
- name: Install snap core
  become: true
  become_user: root
  shell: snap install core
- name: Refreshing snap core
  become: true
  become_user: root
  shell: snap refresh core --candidate
