---
- name: Remove microk8s
  community.general.snap:
    name: microk8s
    state: absent
  retries: 5
  delay: 60
  register: result
  until: "result is not failed"
- name: Delete microk8s group
  ansible.builtin.group:
    name: microk8s
    state: absent