---
- hosts: all
  become: true
  roles:
    - role: roles/k3s-dependencies

- hosts: server
  become: true
  roles:
    - role: roles/k3s-install-server

- hosts: agent
  become: true
  roles:
    - role: roles/k3s-install-agent

- hosts: server
  become: true
  roles:
    - role: roles/k3s-gen-kube-config
