---
- hosts: all
  become: true
  pre_tasks:
    - name: Import common variables
      include_vars: group_vars/common.yml
  roles:
    - role: roles/kube-common 
    - role: roles/microk8s-dependencies
    - role: roles/microk8s-install
      vars:
        primary_user_for_group: "{{ primary_user }}"

- hosts: control
  become: true
  roles:
    - role: roles/microk8s-control

- hosts: worker
  become: true
  roles:
    - role: roles/microk8s-worker

- hosts: control
  become: true
  roles:
    - role: roles/microk8s-wait-ready
    - role: roles/microk8s-gen-kube-config
    - role: roles/microk8s-post-install
