---
- hosts: "{{ hosts | default('all') }}"
  become: true
  become_user: root
  tasks:
    - name: Update all debian server
      ansible.builtin.include_tasks:
        file: roles/debian/tasks/routine_update.yml