---
- name: Ansible find files in subdirectory examples
  find:
    paths: /boot
    patterns: 'cmdline.txt'
    recurse: yes
  register: find_result
- name: Modify cmdline.txt
  become: yes
  become_user: root
  lineinfile:
    path: "{{ find_result.files[0].path }}"
    regex: "^(console=.*splash)$"
    backrefs: yes
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    state: present
  register: result
- name: Fail if local to prompt reboot
  ansible.builtin.fail:
    msg: You're installing server locally; reboot manually and re-run playbook.
  when:
    - result.changed
    - inventory_hostname  == 'localhost'  
- name: Reboot after updating cmdline.txt
  become: yes
  become_user: root
  when:
    - result.changed
    - inventory_hostname  != 'localhost'
  reboot:
    reboot_timeout: 600