- name: Getting join command from the master node…
  become: true
  become_user: root
  shell: microk8s.add-node --format short --token-ttl 3600
  register: join_command
         
- name: Setting join command…
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"
    cachable: true
