---
- name: Modify cmdline.txt
  become: yes
  become_user: root
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regex: "^(console=.*splash)$"
    backrefs: yes
    line: '\1 cgroup_enable=memory cgroup_memory=1'
    state: present
  register: result
- name: Reboot after updating cmdline.txt
  become: yes
  become_user: root
  when: result.changed
  reboot:
    reboot_timeout: 600
