---
- name: Get admin token
  become: yes
  become_user: root
  shell: "/snap/bin/microk8s.config"
  register: k8s_config
- name: Output configuration
  ansible.builtin.debug:
    msg: "{{ k8s_config.stdout }}"
  register: k8s_config
- name: Write variable to file
  local_action: copy content="{{ k8s_config.msg }}" dest=~/k8s-config