---
- name: Install linux-modules-extra-raspi
  ansible.builtin.apt:
    name: linux-modules-extra-raspi
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_architecture == 'aarch64'
    - ansible_kernel is match(".*raspi$")
- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present