---
- name: Getting join command from the master node…
  shell: /snap/bin/microk8s.add-node --format short --token-ttl 3600
  args:
    executable: /bin/bash
  register: join_command
- name: Setting join command…
  set_fact:
    join_command: "/snap/bin/{{ join_command.stdout_lines[0] }}"
    cachable: true
